--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/UnknownNull/Casino
build-by-default: true
branches:
- main
projects:
  Casino:
    path: ""
    lint:
      phpstan: false
    icon: icon.png
    libs:
      - src: Vecnavium/FormsUI
        version: ^1.1.3
...
